/*
 * amazing_client.h
 *
 */

typedef struct AM_Args {
    int avatarId;       // integer generated by AMStartup for each avatar
    int nAvatars;       // total number of avatars
    int difficulty;     // difficulty of tha maze
    char *ipAddress;    // IP address of the server
    uint32_t mazePort;  // MazePort returned in AM_INIT_OK
    char *logfile;      // filename to append to
} AM_Args;

typedef struct Move {
    XYPos pos;
    char direction;
} Move;

void *new_amazing_client(AM_Args *args);

void freeAMArgs(AM_Args *args);